default: &default
 adapter: postgresql
 pool: 5
 encoding: unicode
 username: postgres

development:
 <<: *default
 database: hello_app_development

test:
 <<: *default
 database: hello_app_test

production:
 <<: *default
 database: hello_app_production
